apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: demo
#  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  rules:
  - host: demo-tls.k.dev.bitnami.net
    http:
      paths:
      - backend:
          serviceName: demo
          servicePort: 80
