---
apiVersion: v1
kind: Service
metadata:
  name: demo-clusterip
  annotations:
    description: |
      This is a normal service that offers a L3 load balancing done by K8s networking layer.
spec:
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: demo-headless
  annotations:
    description: |
      This is a headless service. It has no IP address and k8s does no load balancing.
      Instead, it's DNS name contains multiple A records pointing to the individual pods matching the selector.
spec:
  clusterIP: None # headless
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
      name: grpc
